### ISSUE TITLE
请将我的名字从作者列表中删除，谢谢。

### ISSUE THREAD

**Issue by ArchiDog1998** [moewcorp/AutoAction#13]
Please remove my name from author list.

https://github.com/moewcorp/AutoAction/blob/ae66c5b284737ac90b40646701f2a7c1d72d5fc3/XIVAutoAction/AutoAction_CN.yaml#L2

https://github.com/moewcorp/AutoAction/blob/ae66c5b284737ac90b40646701f2a7c1d72d5fc3/XIVAutoAction/AutoAction.yaml#L2

https://github.com/moewcorp/AutoAction/blob/ae66c5b284737ac90b40646701f2a7c1d72d5fc3/pluginmaster_CN.json#L6

https://github.com/moewcorp/AutoAction/blob/ae66c5b284737ac90b40646701f2a7c1d72d5fc3/pluginmaster.json#L6

https://github.com/moewcorp/AutoAction/blob/ae66c5b284737ac90b40646701f2a7c1d72d5fc3/XIVAutoAction/Localization/Strings.cs#L185

**Comment by gamous** [comment]
由于

**Comment by gamous** [comment]
由于GPL协议的要求，必须在产品中注明所有原作者，因此该要求可能不能成立，非常抱歉。

**Comment by gamous** [comment]
同时，提issue是会导致contributor关系成立的，因此该仓库将应原作者要求删除重置一次
