### ISSUE TITLE
恢复Fork关系

### ISSUE THREAD

**Issue by ArchiDog1998** [moewcorp/AutoAction#15]
本仓库既然在Readme中说了是我的仓库的一个Fork，为何没Fork呢？
另外请注明，尽管是一个Fork，但并非原作者指定的进一步维护的社区，而是自发维护。

**Comment by ArchiDog1998** [comment]
能毁掉一个插件的，不是咸鱼小店的插件转卖，而是开发者的懈怠。

**Comment by gamous** [comment]
因为fork是一种客观上继承使用.git文件并声明的形式而非github网站上的数据词条关系，fork关系可以是远程到本地，也可以是从一个托管网站到另一个托管网站。而继续使用.git文件可以保留所有contributor的署名，这是gpl协议的必要要求。
本仓库非原作者指定仓库，是因为原作者放弃继续维护开发而根据GPL协议继续使用代码进行社区自发维护的一个Fork，和原作者只有使用了其开源代码的关系。
插件只是游戏的一个产物，不是一项工作，游戏嘛，开心最重要。Take it easy，enjoy~
